{{- $graf := .Values.observabilitySpec.grafana }}
{{- if $graf.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $graf.datasourceConfigMapName }}
  labels:
    {{- include "vllm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
{{ tpl (.Files.Get "configs/grafana/provisioning/datasources/prometheus.yml") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $graf.dashboardProviderConfigMapName }}
  labels:
    {{- include "vllm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  dashboards.yaml: |
{{ tpl (.Files.Get "configs/grafana/provisioning/dashboards/dashboard.yml") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $graf.dashboardConfigMapName }}
  labels:
    {{- include "vllm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  vllm-a100.json: |
{{ .Files.Get "configs/grafana/dashboards/vllm-a100.json" | indent 4 }}
{{- end }}