<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Payment</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\WolverineDistributed.ServiceDefaults\WolverineDistributed.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Payment\Payment.csproj" />
  </ItemGroup>

</Project>
