<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Catalogs\ECommerce.Services.Catalogs\ECommerce.Services.Catalogs.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
    <ProjectReference Include="..\ECommerce.Services.Catalogs.TestShared\ECommerce.Services.Catalogs.TestShared.csproj" />
  </ItemGroup>

</Project>