<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Orders\ECommerce.Services.Orders.Api\ECommerce.Services.Orders.Api.csproj" />
    <ProjectReference Include="..\..\..\..\src\Services\Orders\ECommerce.Services.Orders\ECommerce.Services.Orders.csproj" />
    <ProjectReference Include="..\ECommerce.Services.Orders.TestShared\ECommerce.Services.Orders.TestShared.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

</Project>