apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: false
  uid: prometheus-uid

- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  editable: false
  uid: tempo-uid
  jsonData:
    httpMethod: GET
    tracesToLogsV2:
      datasourceUid: loki-uid
      spanStartTimeShift: '-5m'
      spanEndTimeShift: '5m'
      tags:
      - key: service_name
        value: service_name
    tracesToMetrics:
      datasourceUid: prometheus-uid
      spanStartTimeShift: '-5m'
      spanEndTimeShift: '5m'
    serviceMap:
      datasourceUid: prometheus-uid
    streamingEnabled:
      search: true

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: false
  uid: loki-uid
  jsonData:
    derivedFields:
    - datasourceUid: tempo-uid
      matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
      name: traceId
      url: '$${__value.raw}'

- name: Elasticsearch
  type: elasticsearch
  access: proxy
  url: http://elasticsearch:9200
  editable: true
  uid: elasticsearch-uid
  jsonData:
    index: "logs-generic-default"
    esVersion: "8.15.2"
    timeField: "@timestamp"
    maxConcurrentShardRequests: 10
    logMessageField: "body_text"
    logLevelField: "severity_text"
