# https://containers.dev/guide/dockerfile#docker-compose-image
# https://containers.dev/guide/dockerfile#docker-compose-dockerfile
services:
  devcontainer:
    build:
      context: .
    volumes:
      - ../..:/workspaces:rw,cached
    init: true
    command: sleep infinity
