# https://containers.dev/guide/dockerfile#dockerfile
# https://github.com/devcontainers/images/tree/main/src/dotnet
# https://github.com/devcontainers/templates/tree/main/src/dotnet

FROM mcr.microsoft.com/devcontainers/dotnet:7.0

# Add additional commands
