<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Orders\ECommerce.Services.Orders\ECommerce.Services.Orders.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
    <ProjectReference Include="..\ECommerce.Services.Orders.TestShared\ECommerce.Services.Orders.TestShared.csproj" />
  </ItemGroup>

</Project>