<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Orders\ECommerce.Services.Orders\ECommerce.Services.Orders.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="$(XunitVersion)" />
  </ItemGroup>
</Project>