{
 "title": "Agentgateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(agentgateway_build_info,namespace)"
   },
   {
    "name": "gateway_name",
    "label": "Gateway",
    "query": "label_values(agentgateway_build_info{namespace=~\"$namespace\"},gateway_networking_k8s_io_gateway_name)"
   },
   {
    "name": "gateway",
    "label": "Gateway Full Name",
    "query": "label_values(agentgateway_requests_total,gateway)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(agentgateway_build_info{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\"})"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (container_memory_working_set_bytes{image=\"\",namespace=~\"$namespace\"}) * on(pod, namespace) group_left(gateway_networking_k8s_io_gateway_name) agentgateway_build_info{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (irate(container_cpu_usage_seconds_total{image=\"\",namespace=~\"$namespace\"}[$__rate_interval]) * on(pod, namespace) group_left(gateway_networking_k8s_io_gateway_name) agentgateway_build_info{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\"})",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests (by Pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (rate(agentgateway_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Requests (by Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (gateway) (rate(agentgateway_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
     "legendFormat": "{{gateway}}"
    }
   ]
  },
  {
   "title": "Requests (by Status)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (gateway,status) (rate(agentgateway_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
     "legendFormat": "{{gateway}}: {{status}}"
    }
   ]
  },
  {
   "title": "Requests (by Reason)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (gateway,reason) (rate(agentgateway_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
     "legendFormat": "{{gateway}}: {{reason}}"
    }
   ]
  },
  {
   "title": "LLM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token Consumption",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (gen_ai_token_type,gen_ai_request_model,gateway) (rate(agentgateway_gen_ai_client_token_usage_sum{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
       "legendFormat": "{{gateway}}: {{gen_ai_request_model}} ({{gen_ai_token_type}})"
      }
     ]
    },
    {
     "title": "USD Cost per Interval",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (gen_ai_request_model,gateway) (increase(agentgateway_gen_ai_client_cost_usd_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
       "legendFormat": "{{gateway}}: {{gen_ai_request_model}}"
      }
     ]
    },
    {
     "title": "Time To First Token",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le,gateway,gen_ai_request_model) (rate(agentgateway_gen_ai_server_time_to_first_token_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))",
       "legendFormat": "{{gateway}}: {{gen_ai_request_model}}"
      }
     ]
    },
    {
     "title": "Request Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le,gateway,gen_ai_request_model) (rate(agentgateway_gen_ai_server_request_duration_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))",
       "legendFormat": "{{gateway}}: {{gen_ai_request_model}}"
      }
     ]
    },
    {
     "title": "Tokens Per Second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "1 / histogram_quantile(0.5, sum by (le,gateway,gen_ai_request_model) (rate(agentgateway_gen_ai_server_time_per_output_token_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))",
       "legendFormat": "{{gateway}}: {{gen_ai_request_model}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "MCP Calls (by method)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (gateway,method) (rate(agentgateway_mcp_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))",
       "legendFormat": "{{gateway}}: {{method}}"
      }
     ]
    },
    {
     "title": "Tool Calls (by tool)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (gateway,server,resource) (rate(agentgateway_mcp_requests_total{namespace=~\"$namespace\",gateway=~\"$gateway\",method=\"tools/call\"}[$__rate_interval]))",
       "legendFormat": "{{gateway}}: {{server}}/{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency by Route",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))) == (histogram_quantile(0.50, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))))",
       "legendFormat": "{{gateway}}: {{route}} p50"
      },
      {
       "expr": "(histogram_quantile(0.95, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))) == (histogram_quantile(0.95, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))))",
       "legendFormat": "{{gateway}}: {{route}} p95"
      },
      {
       "expr": "(histogram_quantile(0.99, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval])))) == (histogram_quantile(0.99, sum by (le,gateway,route) (rate(agentgateway_request_duration_seconds_bucket{namespace=~\"$namespace\",gateway=~\"$gateway\"}[$__rate_interval]))))",
       "legendFormat": "{{gateway}}: {{route}} p99"
      }
     ]
    }
   ]
  },
  {
   "title": "XDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "XDS Messages by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "sum by (url) (rate(agentgateway_xds_message_total[$__rate_interval]))",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "XDS Average Message Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (url) (rate(agentgateway_xds_message_bytes_total[$__rate_interval])) / sum by (url) (rate(agentgateway_xds_message_total[$__rate_interval]))",
       "legendFormat": "{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cgroup Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "agentgateway_cgroup_usage{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} usage"
      },
      {
       "expr": "agentgateway_cgroup_working_set{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} working set"
      },
      {
       "expr": "agentgateway_cgroup_anon{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} anonymous"
      },
      {
       "expr": "agentgateway_cgroup_file{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} file"
      },
      {
       "expr": "agentgateway_cgroup_kernel{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} kernel"
      },
      {
       "expr": "agentgateway_cgroup_sock{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} socket"
      },
      {
       "expr": "agentgateway_cgroup_slab{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} slab"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "agentgateway_process_rss{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} rss"
      },
      {
       "expr": "agentgateway_process_pss{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} pss"
      },
      {
       "expr": "agentgateway_process_private_dirty{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} private dirty"
      },
      {
       "expr": "agentgateway_process_private_clean{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} private clean"
      },
      {
       "expr": "agentgateway_process_shared_clean{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} shared clean"
      },
      {
       "expr": "agentgateway_process_swap{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} swap"
      }
     ]
    },
    {
     "title": "Tokio Runtime",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "agentgateway_tokio_num_workers{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} workers"
      },
      {
       "expr": "agentgateway_tokio_num_alive_tasks{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} alive tasks"
      },
      {
       "expr": "agentgateway_tokio_global_queue_depth{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}/{{pod}} global queue depth"
      }
     ]
    },
    {
     "title": "Build Versions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "sum by (tag) (agentgateway_build_info{namespace=~\"$namespace\",gateway_networking_k8s_io_gateway_name=~\"$gateway_name\",pod=~\"$pod\"})",
       "legendFormat": "{{tag}}"
      }
     ]
    }
   ]
  }
 ]
}