<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Catalogs\ECommerce.Services.Catalogs\ECommerce.Services.Catalogs.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
    <ProjectReference Include="..\ECommerce.Services.Catalogs.TestShared\ECommerce.Services.Catalogs.TestShared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>