<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\BuildingBlocks.Integration.Wolverine\BuildingBlocks.Integration.Wolverine.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\BuildingBlocks.Integration.Wolverine.Kafka\BuildingBlocks.Integration.Wolverine.Kafka.csproj" />
    <ProjectReference Include="..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

</Project>
