<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OrderSaga</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="6.22.0" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.22.0" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="6.22.0" />
    <PackageReference Include="WolverineFx.Postgresql" Version="6.22.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Contracts\Contracts.csproj" />
  </ItemGroup>

</Project>
