<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <ProjectReference Include="..\ECommerce.Services.Orders\ECommerce.Services.Orders.csproj" />
    <ProjectReference Include="..\..\..\Aspire\ECommerce.ServiceDefaults\ECommerce.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>