<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.3" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.3" />
    <PackageReference Include="MassTransit.Kafka" Version="8.5.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <ProjectReference Include="..\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\Services\Shared\ECommerce.Services.Shared\ECommerce.Services.Shared.csproj" />
  </ItemGroup>
</Project>