<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.Kafka" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="..\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\Services\Shared\ECommerce.Services.Shared\ECommerce.Services.Shared.csproj" />
  </ItemGroup>
</Project>