<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Shared\ECommerce.Services.Shared\ECommerce.Services.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.0" />
    <PackageReference Include="MassTransit" Version="8.5.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="Respawn" Version="6.2.1" />
    <PackageReference Include="Testcontainers.Kafka" Version="4.8.1" />
    <PackageReference Include="Testcontainers.MongoDb" Version="4.8.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.8.1" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.8.1" />
    <PackageReference Include="xunit.v3.assert" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="$(XunitVersion)" />
  </ItemGroup>
</Project>