<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\BuildingBlocks.Integration.Wolverine\BuildingBlocks.Integration.Wolverine.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\BuildingBlocks.Integration.Wolverine.RabbitMQ\BuildingBlocks.Integration.Wolverine.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

</Project>
