<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BuildingBlocks.Core</AssemblyName>
    <RootNamespace>BuildingBlocks.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!--https://github.com/dotnet/aspnetcore/issues/19481-->
    <!--https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app-->
    <!--https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore-->
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
  
</Project>
